run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - gocheckcompilerdirectives
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  disable:
    - usestdlibvars
    - errcheck
linters-settings:
  staticcheck:
    checks:
      - all
      - -SA1019 # omit Deprecated check
issues:
  exclude-dirs:
    - core/inference/llama
    - core/inference/ggml
    - core/_echobeats.disabled
    - core/_autonomous.disabled
    - core/_integration.disabled
    - core/_opencog.disabled
    - core/_hgql.disabled
    - _archive
    - _disabled
    - examples
    - Source
    - dev-tools
severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
      severity: info
