// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: echobridge.proto

package echobridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType enumeration
type EventType int32

const (
	EventType_EVENT_UNKNOWN               EventType = 0
	EventType_EVENT_THOUGHT               EventType = 1
	EventType_EVENT_PERCEPTION            EventType = 2
	EventType_EVENT_ACTION                EventType = 3
	EventType_EVENT_LEARNING              EventType = 4
	EventType_EVENT_MEMORY_CONSOLIDATION  EventType = 5
	EventType_EVENT_GOAL_PURSUIT          EventType = 6
	EventType_EVENT_SOCIAL_INTERACTION    EventType = 7
	EventType_EVENT_INTROSPECTION         EventType = 8
	EventType_EVENT_DREAM                 EventType = 9
	EventType_EVENT_WAKE                  EventType = 10
	EventType_EVENT_REST                  EventType = 11
	EventType_EVENT_SKILL_PRACTICE        EventType = 12
	EventType_EVENT_KNOWLEDGE_INTEGRATION EventType = 13
	EventType_EVENT_PATTERN_RECOGNITION   EventType = 14
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_UNKNOWN",
		1:  "EVENT_THOUGHT",
		2:  "EVENT_PERCEPTION",
		3:  "EVENT_ACTION",
		4:  "EVENT_LEARNING",
		5:  "EVENT_MEMORY_CONSOLIDATION",
		6:  "EVENT_GOAL_PURSUIT",
		7:  "EVENT_SOCIAL_INTERACTION",
		8:  "EVENT_INTROSPECTION",
		9:  "EVENT_DREAM",
		10: "EVENT_WAKE",
		11: "EVENT_REST",
		12: "EVENT_SKILL_PRACTICE",
		13: "EVENT_KNOWLEDGE_INTEGRATION",
		14: "EVENT_PATTERN_RECOGNITION",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN":               0,
		"EVENT_THOUGHT":               1,
		"EVENT_PERCEPTION":            2,
		"EVENT_ACTION":                3,
		"EVENT_LEARNING":              4,
		"EVENT_MEMORY_CONSOLIDATION":  5,
		"EVENT_GOAL_PURSUIT":          6,
		"EVENT_SOCIAL_INTERACTION":    7,
		"EVENT_INTROSPECTION":         8,
		"EVENT_DREAM":                 9,
		"EVENT_WAKE":                  10,
		"EVENT_REST":                  11,
		"EVENT_SKILL_PRACTICE":        12,
		"EVENT_KNOWLEDGE_INTEGRATION": 13,
		"EVENT_PATTERN_RECOGNITION":   14,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_echobridge_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_echobridge_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{0}
}

// ThoughtType enumeration
type ThoughtType int32

const (
	ThoughtType_THOUGHT_UNKNOWN     ThoughtType = 0
	ThoughtType_THOUGHT_PERCEPTION  ThoughtType = 1
	ThoughtType_THOUGHT_REFLECTION  ThoughtType = 2
	ThoughtType_THOUGHT_PLANNING    ThoughtType = 3
	ThoughtType_THOUGHT_INSIGHT     ThoughtType = 4
	ThoughtType_THOUGHT_QUESTION    ThoughtType = 5
	ThoughtType_THOUGHT_MEMORY      ThoughtType = 6
	ThoughtType_THOUGHT_IMAGINATION ThoughtType = 7
)

// Enum value maps for ThoughtType.
var (
	ThoughtType_name = map[int32]string{
		0: "THOUGHT_UNKNOWN",
		1: "THOUGHT_PERCEPTION",
		2: "THOUGHT_REFLECTION",
		3: "THOUGHT_PLANNING",
		4: "THOUGHT_INSIGHT",
		5: "THOUGHT_QUESTION",
		6: "THOUGHT_MEMORY",
		7: "THOUGHT_IMAGINATION",
	}
	ThoughtType_value = map[string]int32{
		"THOUGHT_UNKNOWN":     0,
		"THOUGHT_PERCEPTION":  1,
		"THOUGHT_REFLECTION":  2,
		"THOUGHT_PLANNING":    3,
		"THOUGHT_INSIGHT":     4,
		"THOUGHT_QUESTION":    5,
		"THOUGHT_MEMORY":      6,
		"THOUGHT_IMAGINATION": 7,
	}
)

func (x ThoughtType) Enum() *ThoughtType {
	p := new(ThoughtType)
	*p = x
	return p
}

func (x ThoughtType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThoughtType) Descriptor() protoreflect.EnumDescriptor {
	return file_echobridge_proto_enumTypes[1].Descriptor()
}

func (ThoughtType) Type() protoreflect.EnumType {
	return &file_echobridge_proto_enumTypes[1]
}

func (x ThoughtType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThoughtType.Descriptor instead.
func (ThoughtType) EnumDescriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{1}
}

// State enumeration
type State int32

const (
	State_STATE_UNKNOWN      State = 0
	State_STATE_INITIALIZING State = 1
	State_STATE_WAKING       State = 2
	State_STATE_ACTIVE       State = 3
	State_STATE_TIRING       State = 4
	State_STATE_RESTING      State = 5
	State_STATE_DREAMING     State = 6
	State_STATE_SHUTDOWN     State = 7
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_INITIALIZING",
		2: "STATE_WAKING",
		3: "STATE_ACTIVE",
		4: "STATE_TIRING",
		5: "STATE_RESTING",
		6: "STATE_DREAMING",
		7: "STATE_SHUTDOWN",
	}
	State_value = map[string]int32{
		"STATE_UNKNOWN":      0,
		"STATE_INITIALIZING": 1,
		"STATE_WAKING":       2,
		"STATE_ACTIVE":       3,
		"STATE_TIRING":       4,
		"STATE_RESTING":      5,
		"STATE_DREAMING":     6,
		"STATE_SHUTDOWN":     7,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_echobridge_proto_enumTypes[2].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_echobridge_proto_enumTypes[2]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{2}
}

// GoalStatus enumeration
type GoalStatus int32

const (
	GoalStatus_GOAL_UNKNOWN   GoalStatus = 0
	GoalStatus_GOAL_PENDING   GoalStatus = 1
	GoalStatus_GOAL_ACTIVE    GoalStatus = 2
	GoalStatus_GOAL_COMPLETED GoalStatus = 3
	GoalStatus_GOAL_PAUSED    GoalStatus = 4
	GoalStatus_GOAL_ABANDONED GoalStatus = 5
)

// Enum value maps for GoalStatus.
var (
	GoalStatus_name = map[int32]string{
		0: "GOAL_UNKNOWN",
		1: "GOAL_PENDING",
		2: "GOAL_ACTIVE",
		3: "GOAL_COMPLETED",
		4: "GOAL_PAUSED",
		5: "GOAL_ABANDONED",
	}
	GoalStatus_value = map[string]int32{
		"GOAL_UNKNOWN":   0,
		"GOAL_PENDING":   1,
		"GOAL_ACTIVE":    2,
		"GOAL_COMPLETED": 3,
		"GOAL_PAUSED":    4,
		"GOAL_ABANDONED": 5,
	}
)

func (x GoalStatus) Enum() *GoalStatus {
	p := new(GoalStatus)
	*p = x
	return p
}

func (x GoalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_echobridge_proto_enumTypes[3].Descriptor()
}

func (GoalStatus) Type() protoreflect.EnumType {
	return &file_echobridge_proto_enumTypes[3]
}

func (x GoalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalStatus.Descriptor instead.
func (GoalStatus) EnumDescriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{3}
}

// CognitiveEvent represents an event in the cognitive loop
type CognitiveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=echobridge.EventType" json:"type,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // Unix timestamp in milliseconds
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Context       map[string]string      `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Recurring     bool                   `protobuf:"varint,7,opt,name=recurring,proto3" json:"recurring,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,8,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Interval in milliseconds for recurring events
	EngineId      int32                  `protobuf:"varint,9,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`       // Which of the 3 engines should process this (0-2)
	StepId        int32                  `protobuf:"varint,10,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`            // Which of the 12 steps this belongs to (0-11)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CognitiveEvent) Reset() {
	*x = CognitiveEvent{}
	mi := &file_echobridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CognitiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CognitiveEvent) ProtoMessage() {}

func (x *CognitiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CognitiveEvent.ProtoReflect.Descriptor instead.
func (*CognitiveEvent) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{0}
}

func (x *CognitiveEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CognitiveEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNKNOWN
}

func (x *CognitiveEvent) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CognitiveEvent) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *CognitiveEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CognitiveEvent) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CognitiveEvent) GetRecurring() bool {
	if x != nil {
		return x.Recurring
	}
	return false
}

func (x *CognitiveEvent) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *CognitiveEvent) GetEngineId() int32 {
	if x != nil {
		return x.EngineId
	}
	return 0
}

func (x *CognitiveEvent) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

// Thought represents a generated thought
type Thought struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ThoughtType   ThoughtType            `protobuf:"varint,2,opt,name=thought_type,json=thoughtType,proto3,enum=echobridge.ThoughtType" json:"thought_type,omitempty"`
	EnergyLevel   float64                `protobuf:"fixed64,3,opt,name=energy_level,json=energyLevel,proto3" json:"energy_level,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	EngineId      int32                  `protobuf:"varint,6,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"` // Which engine generated this
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thought) Reset() {
	*x = Thought{}
	mi := &file_echobridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thought) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thought) ProtoMessage() {}

func (x *Thought) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thought.ProtoReflect.Descriptor instead.
func (*Thought) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{1}
}

func (x *Thought) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Thought) GetThoughtType() ThoughtType {
	if x != nil {
		return x.ThoughtType
	}
	return ThoughtType_THOUGHT_UNKNOWN
}

func (x *Thought) GetEnergyLevel() float64 {
	if x != nil {
		return x.EnergyLevel
	}
	return 0
}

func (x *Thought) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Thought) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Thought) GetEngineId() int32 {
	if x != nil {
		return x.EngineId
	}
	return 0
}

func (x *Thought) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CognitiveState represents the current state of the system
type CognitiveState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Energy            float64                `protobuf:"fixed64,1,opt,name=energy,proto3" json:"energy,omitempty"`
	Fatigue           float64                `protobuf:"fixed64,2,opt,name=fatigue,proto3" json:"fatigue,omitempty"`
	Coherence         float64                `protobuf:"fixed64,3,opt,name=coherence,proto3" json:"coherence,omitempty"`
	Curiosity         float64                `protobuf:"fixed64,4,opt,name=curiosity,proto3" json:"curiosity,omitempty"`
	CurrentState      State                  `protobuf:"varint,5,opt,name=current_state,json=currentState,proto3,enum=echobridge.State" json:"current_state,omitempty"`
	LastRestTimestamp int64                  `protobuf:"varint,6,opt,name=last_rest_timestamp,json=lastRestTimestamp,proto3" json:"last_rest_timestamp,omitempty"`
	CyclesSinceRest   int32                  `protobuf:"varint,7,opt,name=cycles_since_rest,json=cyclesSinceRest,proto3" json:"cycles_since_rest,omitempty"`
	// 3-Engine specific state
	Engine_0State *EngineState `protobuf:"bytes,8,opt,name=engine_0_state,json=engine0State,proto3" json:"engine_0_state,omitempty"`  // Memory Engine (Past)
	Engine_1State *EngineState `protobuf:"bytes,9,opt,name=engine_1_state,json=engine1State,proto3" json:"engine_1_state,omitempty"`  // Coherence Engine (Present)
	Engine_2State *EngineState `protobuf:"bytes,10,opt,name=engine_2_state,json=engine2State,proto3" json:"engine_2_state,omitempty"` // Imagination Engine (Future)
	CurrentStep   int32        `protobuf:"varint,11,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`     // Current step in 12-step loop (0-11)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CognitiveState) Reset() {
	*x = CognitiveState{}
	mi := &file_echobridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CognitiveState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CognitiveState) ProtoMessage() {}

func (x *CognitiveState) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CognitiveState.ProtoReflect.Descriptor instead.
func (*CognitiveState) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{2}
}

func (x *CognitiveState) GetEnergy() float64 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *CognitiveState) GetFatigue() float64 {
	if x != nil {
		return x.Fatigue
	}
	return 0
}

func (x *CognitiveState) GetCoherence() float64 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *CognitiveState) GetCuriosity() float64 {
	if x != nil {
		return x.Curiosity
	}
	return 0
}

func (x *CognitiveState) GetCurrentState() State {
	if x != nil {
		return x.CurrentState
	}
	return State_STATE_UNKNOWN
}

func (x *CognitiveState) GetLastRestTimestamp() int64 {
	if x != nil {
		return x.LastRestTimestamp
	}
	return 0
}

func (x *CognitiveState) GetCyclesSinceRest() int32 {
	if x != nil {
		return x.CyclesSinceRest
	}
	return 0
}

func (x *CognitiveState) GetEngine_0State() *EngineState {
	if x != nil {
		return x.Engine_0State
	}
	return nil
}

func (x *CognitiveState) GetEngine_1State() *EngineState {
	if x != nil {
		return x.Engine_1State
	}
	return nil
}

func (x *CognitiveState) GetEngine_2State() *EngineState {
	if x != nil {
		return x.Engine_2State
	}
	return nil
}

func (x *CognitiveState) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

// EngineState represents the state of one of the 3 inference engines
type EngineState struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EngineId              int32                  `protobuf:"varint,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	EngineName            string                 `protobuf:"bytes,2,opt,name=engine_name,json=engineName,proto3" json:"engine_name,omitempty"`
	Active                bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	ProcessingLoad        float64                `protobuf:"fixed64,4,opt,name=processing_load,json=processingLoad,proto3" json:"processing_load,omitempty"`
	ThoughtsGenerated     int64                  `protobuf:"varint,5,opt,name=thoughts_generated,json=thoughtsGenerated,proto3" json:"thoughts_generated,omitempty"`
	LastActivityTimestamp int64                  `protobuf:"varint,6,opt,name=last_activity_timestamp,json=lastActivityTimestamp,proto3" json:"last_activity_timestamp,omitempty"`
	CurrentFocus          string                 `protobuf:"bytes,7,opt,name=current_focus,json=currentFocus,proto3" json:"current_focus,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EngineState) Reset() {
	*x = EngineState{}
	mi := &file_echobridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineState) ProtoMessage() {}

func (x *EngineState) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineState.ProtoReflect.Descriptor instead.
func (*EngineState) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{3}
}

func (x *EngineState) GetEngineId() int32 {
	if x != nil {
		return x.EngineId
	}
	return 0
}

func (x *EngineState) GetEngineName() string {
	if x != nil {
		return x.EngineName
	}
	return ""
}

func (x *EngineState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EngineState) GetProcessingLoad() float64 {
	if x != nil {
		return x.ProcessingLoad
	}
	return 0
}

func (x *EngineState) GetThoughtsGenerated() int64 {
	if x != nil {
		return x.ThoughtsGenerated
	}
	return 0
}

func (x *EngineState) GetLastActivityTimestamp() int64 {
	if x != nil {
		return x.LastActivityTimestamp
	}
	return 0
}

func (x *EngineState) GetCurrentFocus() string {
	if x != nil {
		return x.CurrentFocus
	}
	return ""
}

// Goal represents a cognitive goal
type Goal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Progress       float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Target         float64                `protobuf:"fixed64,6,opt,name=target,proto3" json:"target,omitempty"`
	Deadline       int64                  `protobuf:"varint,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Status         GoalStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=echobridge.GoalStatus" json:"status,omitempty"`
	RequiredSkills []string               `protobuf:"bytes,9,rep,name=required_skills,json=requiredSkills,proto3" json:"required_skills,omitempty"`
	KnowledgeGaps  []string               `protobuf:"bytes,10,rep,name=knowledge_gaps,json=knowledgeGaps,proto3" json:"knowledge_gaps,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_echobridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{4}
}

func (x *Goal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Goal) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Goal) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Goal) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Goal) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Goal) GetStatus() GoalStatus {
	if x != nil {
		return x.Status
	}
	return GoalStatus_GOAL_UNKNOWN
}

func (x *Goal) GetRequiredSkills() []string {
	if x != nil {
		return x.RequiredSkills
	}
	return nil
}

func (x *Goal) GetKnowledgeGaps() []string {
	if x != nil {
		return x.KnowledgeGaps
	}
	return nil
}

func (x *Goal) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GoalProgress represents progress update for a goal
type GoalProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Progress      float64                `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	UpdateMessage string                 `protobuf:"bytes,3,opt,name=update_message,json=updateMessage,proto3" json:"update_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalProgress) Reset() {
	*x = GoalProgress{}
	mi := &file_echobridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalProgress) ProtoMessage() {}

func (x *GoalProgress) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalProgress.ProtoReflect.Descriptor instead.
func (*GoalProgress) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{5}
}

func (x *GoalProgress) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *GoalProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GoalProgress) GetUpdateMessage() string {
	if x != nil {
		return x.UpdateMessage
	}
	return ""
}

// Request/Response messages
type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_echobridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{6}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type StateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IncludeEngineDetails bool                   `protobuf:"varint,1,opt,name=include_engine_details,json=includeEngineDetails,proto3" json:"include_engine_details,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_echobridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{7}
}

func (x *StateRequest) GetIncludeEngineDetails() bool {
	if x != nil {
		return x.IncludeEngineDetails
	}
	return false
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_echobridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{8}
}

func (x *StateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ThoughtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ThoughtId     string                 `protobuf:"bytes,3,opt,name=thought_id,json=thoughtId,proto3" json:"thought_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtResponse) Reset() {
	*x = ThoughtResponse{}
	mi := &file_echobridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtResponse) ProtoMessage() {}

func (x *ThoughtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtResponse.ProtoReflect.Descriptor instead.
func (*ThoughtResponse) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{9}
}

func (x *ThoughtResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThoughtResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ThoughtResponse) GetThoughtId() string {
	if x != nil {
		return x.ThoughtId
	}
	return ""
}

type EventStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []EventType            `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=echobridge.EventType" json:"event_types,omitempty"` // Filter by event types
	EngineId      int32                  `protobuf:"varint,2,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`                                        // Filter by engine (-1 for all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_echobridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{10}
}

func (x *EventStreamRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventStreamRequest) GetEngineId() int32 {
	if x != nil {
		return x.EngineId
	}
	return 0
}

type GoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  GoalStatus             `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=echobridge.GoalStatus" json:"status_filter,omitempty"` // Filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalRequest) Reset() {
	*x = GoalRequest{}
	mi := &file_echobridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalRequest) ProtoMessage() {}

func (x *GoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalRequest.ProtoReflect.Descriptor instead.
func (*GoalRequest) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{11}
}

func (x *GoalRequest) GetStatusFilter() GoalStatus {
	if x != nil {
		return x.StatusFilter
	}
	return GoalStatus_GOAL_UNKNOWN
}

type GoalList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalList) Reset() {
	*x = GoalList{}
	mi := &file_echobridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalList) ProtoMessage() {}

func (x *GoalList) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalList.ProtoReflect.Descriptor instead.
func (*GoalList) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{12}
}

func (x *GoalList) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

type GoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GoalId        string                 `protobuf:"bytes,3,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalResponse) Reset() {
	*x = GoalResponse{}
	mi := &file_echobridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalResponse) ProtoMessage() {}

func (x *GoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echobridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalResponse.ProtoReflect.Descriptor instead.
func (*GoalResponse) Descriptor() ([]byte, []int) {
	return file_echobridge_proto_rawDescGZIP(), []int{13}
}

func (x *GoalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GoalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GoalResponse) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

var File_echobridge_proto protoreflect.FileDescriptor

const file_echobridge_proto_rawDesc = "" +
	"\n" +
	"\x10echobridge.proto\x12\n" +
	"echobridge\"\x98\x03\n" +
	"\x0eCognitiveEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.echobridge.EventTypeR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x03R\vscheduledAt\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12A\n" +
	"\acontext\x18\x06 \x03(\v2'.echobridge.CognitiveEvent.ContextEntryR\acontext\x12\x1c\n" +
	"\trecurring\x18\a \x01(\bR\trecurring\x12\x1f\n" +
	"\vinterval_ms\x18\b \x01(\x03R\n" +
	"intervalMs\x12\x1b\n" +
	"\tengine_id\x18\t \x01(\x05R\bengineId\x12\x17\n" +
	"\astep_id\x18\n" +
	" \x01(\x05R\x06stepId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x02\n" +
	"\aThought\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12:\n" +
	"\fthought_type\x18\x02 \x01(\x0e2\x17.echobridge.ThoughtTypeR\vthoughtType\x12!\n" +
	"\fenergy_level\x18\x03 \x01(\x01R\venergyLevel\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1b\n" +
	"\tengine_id\x18\x06 \x01(\x05R\bengineId\x12=\n" +
	"\bmetadata\x18\a \x03(\v2!.echobridge.Thought.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x03\n" +
	"\x0eCognitiveState\x12\x16\n" +
	"\x06energy\x18\x01 \x01(\x01R\x06energy\x12\x18\n" +
	"\afatigue\x18\x02 \x01(\x01R\afatigue\x12\x1c\n" +
	"\tcoherence\x18\x03 \x01(\x01R\tcoherence\x12\x1c\n" +
	"\tcuriosity\x18\x04 \x01(\x01R\tcuriosity\x126\n" +
	"\rcurrent_state\x18\x05 \x01(\x0e2\x11.echobridge.StateR\fcurrentState\x12.\n" +
	"\x13last_rest_timestamp\x18\x06 \x01(\x03R\x11lastRestTimestamp\x12*\n" +
	"\x11cycles_since_rest\x18\a \x01(\x05R\x0fcyclesSinceRest\x12=\n" +
	"\x0eengine_0_state\x18\b \x01(\v2\x17.echobridge.EngineStateR\fengine0State\x12=\n" +
	"\x0eengine_1_state\x18\t \x01(\v2\x17.echobridge.EngineStateR\fengine1State\x12=\n" +
	"\x0eengine_2_state\x18\n" +
	" \x01(\v2\x17.echobridge.EngineStateR\fengine2State\x12!\n" +
	"\fcurrent_step\x18\v \x01(\x05R\vcurrentStep\"\x98\x02\n" +
	"\vEngineState\x12\x1b\n" +
	"\tengine_id\x18\x01 \x01(\x05R\bengineId\x12\x1f\n" +
	"\vengine_name\x18\x02 \x01(\tR\n" +
	"engineName\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12'\n" +
	"\x0fprocessing_load\x18\x04 \x01(\x01R\x0eprocessingLoad\x12-\n" +
	"\x12thoughts_generated\x18\x05 \x01(\x03R\x11thoughtsGenerated\x126\n" +
	"\x17last_activity_timestamp\x18\x06 \x01(\x03R\x15lastActivityTimestamp\x12#\n" +
	"\rcurrent_focus\x18\a \x01(\tR\fcurrentFocus\"\xd7\x02\n" +
	"\x04Goal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x16\n" +
	"\x06target\x18\x06 \x01(\x01R\x06target\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\x03R\bdeadline\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.echobridge.GoalStatusR\x06status\x12'\n" +
	"\x0frequired_skills\x18\t \x03(\tR\x0erequiredSkills\x12%\n" +
	"\x0eknowledge_gaps\x18\n" +
	" \x03(\tR\rknowledgeGaps\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"j\n" +
	"\fGoalProgress\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12%\n" +
	"\x0eupdate_message\x18\x03 \x01(\tR\rupdateMessage\"^\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"D\n" +
	"\fStateRequest\x124\n" +
	"\x16include_engine_details\x18\x01 \x01(\bR\x14includeEngineDetails\"C\n" +
	"\rStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x0fThoughtResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"thought_id\x18\x03 \x01(\tR\tthoughtId\"i\n" +
	"\x12EventStreamRequest\x126\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x15.echobridge.EventTypeR\n" +
	"eventTypes\x12\x1b\n" +
	"\tengine_id\x18\x02 \x01(\x05R\bengineId\"J\n" +
	"\vGoalRequest\x12;\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x16.echobridge.GoalStatusR\fstatusFilter\"2\n" +
	"\bGoalList\x12&\n" +
	"\x05goals\x18\x01 \x03(\v2\x10.echobridge.GoalR\x05goals\"[\n" +
	"\fGoalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\agoal_id\x18\x03 \x01(\tR\x06goalId*\xe7\x02\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x11\n" +
	"\rEVENT_THOUGHT\x10\x01\x12\x14\n" +
	"\x10EVENT_PERCEPTION\x10\x02\x12\x10\n" +
	"\fEVENT_ACTION\x10\x03\x12\x12\n" +
	"\x0eEVENT_LEARNING\x10\x04\x12\x1e\n" +
	"\x1aEVENT_MEMORY_CONSOLIDATION\x10\x05\x12\x16\n" +
	"\x12EVENT_GOAL_PURSUIT\x10\x06\x12\x1c\n" +
	"\x18EVENT_SOCIAL_INTERACTION\x10\a\x12\x17\n" +
	"\x13EVENT_INTROSPECTION\x10\b\x12\x0f\n" +
	"\vEVENT_DREAM\x10\t\x12\x0e\n" +
	"\n" +
	"EVENT_WAKE\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"EVENT_REST\x10\v\x12\x18\n" +
	"\x14EVENT_SKILL_PRACTICE\x10\f\x12\x1f\n" +
	"\x1bEVENT_KNOWLEDGE_INTEGRATION\x10\r\x12\x1d\n" +
	"\x19EVENT_PATTERN_RECOGNITION\x10\x0e*\xc0\x01\n" +
	"\vThoughtType\x12\x13\n" +
	"\x0fTHOUGHT_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12THOUGHT_PERCEPTION\x10\x01\x12\x16\n" +
	"\x12THOUGHT_REFLECTION\x10\x02\x12\x14\n" +
	"\x10THOUGHT_PLANNING\x10\x03\x12\x13\n" +
	"\x0fTHOUGHT_INSIGHT\x10\x04\x12\x14\n" +
	"\x10THOUGHT_QUESTION\x10\x05\x12\x12\n" +
	"\x0eTHOUGHT_MEMORY\x10\x06\x12\x17\n" +
	"\x13THOUGHT_IMAGINATION\x10\a*\xa3\x01\n" +
	"\x05State\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12STATE_INITIALIZING\x10\x01\x12\x10\n" +
	"\fSTATE_WAKING\x10\x02\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x03\x12\x10\n" +
	"\fSTATE_TIRING\x10\x04\x12\x11\n" +
	"\rSTATE_RESTING\x10\x05\x12\x12\n" +
	"\x0eSTATE_DREAMING\x10\x06\x12\x12\n" +
	"\x0eSTATE_SHUTDOWN\x10\a*z\n" +
	"\n" +
	"GoalStatus\x12\x10\n" +
	"\fGOAL_UNKNOWN\x10\x00\x12\x10\n" +
	"\fGOAL_PENDING\x10\x01\x12\x0f\n" +
	"\vGOAL_ACTIVE\x10\x02\x12\x12\n" +
	"\x0eGOAL_COMPLETED\x10\x03\x12\x0f\n" +
	"\vGOAL_PAUSED\x10\x04\x12\x12\n" +
	"\x0eGOAL_ABANDONED\x10\x052\xb9\x04\n" +
	"\n" +
	"EchoBridge\x12F\n" +
	"\rScheduleEvent\x12\x1a.echobridge.CognitiveEvent\x1a\x19.echobridge.EventResponse\x12@\n" +
	"\bGetState\x12\x18.echobridge.StateRequest\x1a\x1a.echobridge.CognitiveState\x12D\n" +
	"\vUpdateState\x12\x1a.echobridge.CognitiveState\x1a\x19.echobridge.StateResponse\x12F\n" +
	"\x0eStreamThoughts\x12\x13.echobridge.Thought\x1a\x1b.echobridge.ThoughtResponse(\x010\x01\x12L\n" +
	"\fStreamEvents\x12\x1e.echobridge.EventStreamRequest\x1a\x1a.echobridge.CognitiveEvent0\x01\x12:\n" +
	"\fRegisterGoal\x12\x10.echobridge.Goal\x1a\x18.echobridge.GoalResponse\x12H\n" +
	"\x12UpdateGoalProgress\x12\x18.echobridge.GoalProgress\x1a\x18.echobridge.GoalResponse\x12?\n" +
	"\x0eGetActiveGoals\x12\x17.echobridge.GoalRequest\x1a\x14.echobridge.GoalListB-Z+github.com/cogpy/echo9llama/core/echobridgeb\x06proto3"

var (
	file_echobridge_proto_rawDescOnce sync.Once
	file_echobridge_proto_rawDescData []byte
)

func file_echobridge_proto_rawDescGZIP() []byte {
	file_echobridge_proto_rawDescOnce.Do(func() {
		file_echobridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echobridge_proto_rawDesc), len(file_echobridge_proto_rawDesc)))
	})
	return file_echobridge_proto_rawDescData
}

var file_echobridge_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_echobridge_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_echobridge_proto_goTypes = []any{
	(EventType)(0),             // 0: echobridge.EventType
	(ThoughtType)(0),           // 1: echobridge.ThoughtType
	(State)(0),                 // 2: echobridge.State
	(GoalStatus)(0),            // 3: echobridge.GoalStatus
	(*CognitiveEvent)(nil),     // 4: echobridge.CognitiveEvent
	(*Thought)(nil),            // 5: echobridge.Thought
	(*CognitiveState)(nil),     // 6: echobridge.CognitiveState
	(*EngineState)(nil),        // 7: echobridge.EngineState
	(*Goal)(nil),               // 8: echobridge.Goal
	(*GoalProgress)(nil),       // 9: echobridge.GoalProgress
	(*EventResponse)(nil),      // 10: echobridge.EventResponse
	(*StateRequest)(nil),       // 11: echobridge.StateRequest
	(*StateResponse)(nil),      // 12: echobridge.StateResponse
	(*ThoughtResponse)(nil),    // 13: echobridge.ThoughtResponse
	(*EventStreamRequest)(nil), // 14: echobridge.EventStreamRequest
	(*GoalRequest)(nil),        // 15: echobridge.GoalRequest
	(*GoalList)(nil),           // 16: echobridge.GoalList
	(*GoalResponse)(nil),       // 17: echobridge.GoalResponse
	nil,                        // 18: echobridge.CognitiveEvent.ContextEntry
	nil,                        // 19: echobridge.Thought.MetadataEntry
}
var file_echobridge_proto_depIdxs = []int32{
	0,  // 0: echobridge.CognitiveEvent.type:type_name -> echobridge.EventType
	18, // 1: echobridge.CognitiveEvent.context:type_name -> echobridge.CognitiveEvent.ContextEntry
	1,  // 2: echobridge.Thought.thought_type:type_name -> echobridge.ThoughtType
	19, // 3: echobridge.Thought.metadata:type_name -> echobridge.Thought.MetadataEntry
	2,  // 4: echobridge.CognitiveState.current_state:type_name -> echobridge.State
	7,  // 5: echobridge.CognitiveState.engine_0_state:type_name -> echobridge.EngineState
	7,  // 6: echobridge.CognitiveState.engine_1_state:type_name -> echobridge.EngineState
	7,  // 7: echobridge.CognitiveState.engine_2_state:type_name -> echobridge.EngineState
	3,  // 8: echobridge.Goal.status:type_name -> echobridge.GoalStatus
	0,  // 9: echobridge.EventStreamRequest.event_types:type_name -> echobridge.EventType
	3,  // 10: echobridge.GoalRequest.status_filter:type_name -> echobridge.GoalStatus
	8,  // 11: echobridge.GoalList.goals:type_name -> echobridge.Goal
	4,  // 12: echobridge.EchoBridge.ScheduleEvent:input_type -> echobridge.CognitiveEvent
	11, // 13: echobridge.EchoBridge.GetState:input_type -> echobridge.StateRequest
	6,  // 14: echobridge.EchoBridge.UpdateState:input_type -> echobridge.CognitiveState
	5,  // 15: echobridge.EchoBridge.StreamThoughts:input_type -> echobridge.Thought
	14, // 16: echobridge.EchoBridge.StreamEvents:input_type -> echobridge.EventStreamRequest
	8,  // 17: echobridge.EchoBridge.RegisterGoal:input_type -> echobridge.Goal
	9,  // 18: echobridge.EchoBridge.UpdateGoalProgress:input_type -> echobridge.GoalProgress
	15, // 19: echobridge.EchoBridge.GetActiveGoals:input_type -> echobridge.GoalRequest
	10, // 20: echobridge.EchoBridge.ScheduleEvent:output_type -> echobridge.EventResponse
	6,  // 21: echobridge.EchoBridge.GetState:output_type -> echobridge.CognitiveState
	12, // 22: echobridge.EchoBridge.UpdateState:output_type -> echobridge.StateResponse
	13, // 23: echobridge.EchoBridge.StreamThoughts:output_type -> echobridge.ThoughtResponse
	4,  // 24: echobridge.EchoBridge.StreamEvents:output_type -> echobridge.CognitiveEvent
	17, // 25: echobridge.EchoBridge.RegisterGoal:output_type -> echobridge.GoalResponse
	17, // 26: echobridge.EchoBridge.UpdateGoalProgress:output_type -> echobridge.GoalResponse
	16, // 27: echobridge.EchoBridge.GetActiveGoals:output_type -> echobridge.GoalList
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_echobridge_proto_init() }
func file_echobridge_proto_init() {
	if File_echobridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echobridge_proto_rawDesc), len(file_echobridge_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echobridge_proto_goTypes,
		DependencyIndexes: file_echobridge_proto_depIdxs,
		EnumInfos:         file_echobridge_proto_enumTypes,
		MessageInfos:      file_echobridge_proto_msgTypes,
	}.Build()
	File_echobridge_proto = out.File
	file_echobridge_proto_goTypes = nil
	file_echobridge_proto_depIdxs = nil
}
